package com.crossover.techtrial.service;

import com.crossover.techtrial.model.HourlyElectricity;
import com.crossover.techtrial.model.Panel;
import com.crossover.techtrial.repository.HourlyElectricityRepository;

import java.time.LocalDateTime;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

/**
 * HourlyElectricityServiceImpl will handle electricity generated by a Panel.
 *
 * @author Crossover
 *
 */

@Service
public class HourlyElectricityServiceImpl implements HourlyElectricityService {
	
  @Autowired
  HourlyElectricityRepository hourlyElectricityRepository;
 
  @Autowired
  PanelService panelService;

  public HourlyElectricityServiceImpl(final HourlyElectricityRepository hourlyElectricityRepository,
                                      final PanelService panelService) {
    this.hourlyElectricityRepository = hourlyElectricityRepository;
    this.panelService = panelService;
  }

  @Override
  public HourlyElectricity save(HourlyElectricity hourlyElectricity, String panelSerial) {
    Panel panel = panelService.getBySerial(panelSerial);
    hourlyElectricity.setPanel(panel);

    return hourlyElectricityRepository.save(hourlyElectricity);
  }

  @Override
  public Page<HourlyElectricity> getAllHourlyElectricityByPanelId(String panelSerial, Pageable pageable) {
    Panel panel = panelService.getBySerial(panelSerial);
    return hourlyElectricityRepository.findAllByPanelId(panel.getId(), pageable);
  }

  @Override
  public List<HourlyElectricity> getAllHourlyElectricityByReadingAtBetween(LocalDateTime initialReadingAt, LocalDateTime finalReadingAt, Panel panel) {
    return this.hourlyElectricityRepository.findByReadingAtBetweenAndPanel(initialReadingAt, finalReadingAt, panel);
  }
}